name: Java CI on Windows

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest    # <-- Windows runner

    steps:
      - uses: actions/checkout@v3

      - name: Setup Java JDK
        uses: actions/setup-java@v4.7.1
        with:
          distribution: 'oracle'
          java-version: '17'
          cache: 'maven'
