name: Java CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Java JDK
        uses: actions/setup-java@v4.7.1
        with:
          distribution: 'oracle'
          java-version: '7'        # <- obligatoria: define tu versión
          accept-terms: 'true'      # <- para Oracle JDK debes aceptar la licencia
          cache: 'maven'            # <- opcional, sólo si usas Maven
